/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.predictor.ux;

import static javax.swing.JOptionPane.showMessageDialog;
import java.io.IOException;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.xml.parsers.ParserConfigurationException;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import org.xml.sax.SAXException;
import com.app.predictor.model.PicoPlacaForm;
import com.app.predictor.service.ServicePredictorPicoPlaca;


/**
 * The Class MainWindow.
 *
 * @author root
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow.
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMaster = new javax.swing.JPanel();
        jPanelHead = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonMenuBuscar = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();
        jPanelDetail = new javax.swing.JPanel();
        jPanelDashboard = new javax.swing.JPanel();
        Date dateParam = new Date();
        jDateChooserParam = new com.toedter.calendar.JDateChooser(dateParam);
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        jSpinnerParam = new javax.swing.JSpinner(sm);
        jTextFieldPlaca = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonExecuteSearch = new javax.swing.JButton();
        jPanelAbout = new javax.swing.JPanel();
        jScrollPanelPdfViewer = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Predictor PP");
        setResizable(false);

        jPanelHead.setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prototype Program");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("This program is only for example, contains core Java and Architecture client-server with Spring Framework");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Predictor de Pico y Placa");

        javax.swing.GroupLayout jPanelHeadLayout = new javax.swing.GroupLayout(jPanelHead);
        jPanelHead.setLayout(jPanelHeadLayout);
        jPanelHeadLayout.setHorizontalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeadLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(jPanelHeadLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelHeadLayout.setVerticalGroup(
            jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeadLayout.createSequentialGroup()
                .addGroup(jPanelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanelMenu.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jToolBar1.setRollover(true);

        jButtonMenuBuscar.setText("Dashboard");
        jButtonMenuBuscar.setFocusable(false);
        jButtonMenuBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMenuBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuBuscarActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonMenuBuscar);

        jButtonAbout.setText("About");
        jButtonAbout.setFocusable(false);
        jButtonAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAbout);

        jPanelMenu.add(jToolBar1, java.awt.BorderLayout.CENTER);

        jPanelDetail.setLayout(new java.awt.CardLayout());

        jPanelDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelDashboard.setPreferredSize(new java.awt.Dimension(426, 331));

        JSpinner.DateEditor de = new JSpinner.DateEditor(jSpinnerParam,"HH:mm:ss");
        jSpinnerParam.setEditor(de);

        try {
            jTextFieldPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("***-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Placa:");

        jLabel5.setText("Fecha:");

        jLabel6.setText("Hora:");

        jButtonExecuteSearch.setText("Buscar");
        jButtonExecuteSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonExecuteSearch.setBorderPainted(false);
        jButtonExecuteSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecuteSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4))
                    .addGroup(jPanelDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonExecuteSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerParam, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserParam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(659, Short.MAX_VALUE))
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExecuteSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jPanelDetail.add(jPanelDashboard, "card2");

        try{
            URL location = new URL("http://www.mobilpymes.com/CV_WilliamHuera.pdf");
            this.openPdf(location);}
        catch(Exception ex){
            ex.getMessage();
        }
        //this.openPdf("CV_WilliamHuera.pdf");
        //setExtendedState(MAXIMIZED_BOTH);

        javax.swing.GroupLayout jPanelAboutLayout = new javax.swing.GroupLayout(jPanelAbout);
        jPanelAbout.setLayout(jPanelAboutLayout);
        jPanelAboutLayout.setHorizontalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanelPdfViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
        );
        jPanelAboutLayout.setVerticalGroup(
            jPanelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPanelPdfViewer, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        jPanelDetail.add(jPanelAbout, "card3");

        javax.swing.GroupLayout jPanelMasterLayout = new javax.swing.GroupLayout(jPanelMaster);
        jPanelMaster.setLayout(jPanelMasterLayout);
        jPanelMasterLayout.setHorizontalGroup(
            jPanelMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMasterLayout.setVerticalGroup(
            jPanelMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMasterLayout.createSequentialGroup()
                .addComponent(jPanelHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(jPanelMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMasterLayout.createSequentialGroup()
                    .addGap(0, 144, Short.MAX_VALUE)
                    .addComponent(jPanelDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMaster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * J button 2 action performed.
     *
     * @param evt the evt
     */
    private void jButtonExecuteSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecuteSearchActionPerformed
      
      this.executeProcess();
    }//GEN-LAST:event_jButtonExecuteSearchActionPerformed

    /**
     * J button about action performed.
     *
     * @param evt the evt
     */
    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
//        showMessageDialog(null, "About programmer: William Huera send email to whuera@gmail.com");
        jPanelDetail.removeAll();
        jPanelDetail.repaint();
        jPanelDetail.revalidate();
        jPanelDetail.add(jPanelAbout);
        jPanelDetail.repaint();
        jPanelDetail.revalidate();
        
        
    }//GEN-LAST:event_jButtonAboutActionPerformed

    /**
     * J button menu buscar action performed.
     *
     * @param evt the evt
     */
    private void jButtonMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuBuscarActionPerformed
        // TODO add your handling code here:
        //this.executeProcess();
         jPanelDetail.removeAll();
        jPanelDetail.repaint();
        jPanelDetail.revalidate();
        jPanelDetail.add(jPanelDashboard);
        jPanelDetail.repaint();
        jPanelDetail.revalidate();
        
    }//GEN-LAST:event_jButtonMenuBuscarActionPerformed

    /**
     * Execute process.
     */
    public void executeProcess(){               
         if (jTextFieldPlaca.getText().replace("-", "").trim().length()>4 && !jTextFieldPlaca.getText().replace("-", "").trim().equalsIgnoreCase("") && !jTextFieldPlaca.getText().isEmpty() && !jTextFieldPlaca.getText().equalsIgnoreCase(null) && !jTextFieldPlaca.getText().equalsIgnoreCase("") && jSpinnerParam.getValue().toString() != null){             
            Calendar dateInput = jDateChooserParam.getCalendar();
            ServicePredictorPicoPlaca bussinesRule = new ServicePredictorPicoPlaca();
            PicoPlacaForm picoPlacaForm = new PicoPlacaForm();
            picoPlacaForm.setDateQuestion(dateInput);
            picoPlacaForm.setNumber(jTextFieldPlaca.getText().replace("-",""));
            DateFormat df = new SimpleDateFormat("HH:mm");
            Date today = (Date) jSpinnerParam.getValue();
            String reportDate = df.format(today);
            picoPlacaForm.setParamTime(reportDate);
            try {
                String remoteMessage = bussinesRule.dayEnabled(picoPlacaForm);
                showMessageDialog(null, remoteMessage);
            } catch (SAXException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParserConfigurationException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                jTextFieldPlaca.setText("");
                jTextFieldPlaca.requestFocus();
            }
        }else{
            showMessageDialog(null, "Revise los parametros de ingreso");
        }
    }
    
    /**
     * Open pdf.
     *
     * @param location the location
     */
    public void openPdf(URL location){
        SwingController control = new SwingController();
        SwingViewBuilder factory = new SwingViewBuilder(control);
        JPanel viewerComponent = factory.buildViewerPanel();
        ComponentKeyBinding.install(control, viewerComponent);
        control.getDocumentViewController().setAnnotationCallback(
                new org.icepdf.ri.common.MyAnnotationCallback(
                        control.getDocumentViewController()));
        control.openDocument(location);
        jScrollPanelPdfViewer.setViewportView(viewerComponent);
 
    }
    
    /**
     * The main method.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    /** The j button 2. */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonExecuteSearch;
    private javax.swing.JButton jButtonMenuBuscar;
    private com.toedter.calendar.JDateChooser jDateChooserParam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelAbout;
    private javax.swing.JPanel jPanelDashboard;
    private javax.swing.JPanel jPanelDetail;
    private javax.swing.JPanel jPanelHead;
    private javax.swing.JPanel jPanelMaster;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPanelPdfViewer;
    private javax.swing.JSpinner jSpinnerParam;
    private javax.swing.JFormattedTextField jTextFieldPlaca;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
